{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "conda create -n mysql-client  \n",
    "conda activate mysql-client  \n",
    "conda install python=3.7.12 mysql-connector-python pymysql sqlalchemy=1.3.24 pandas jupyter ipykernel nb_conda_kernels ipywidgets -c conda-forge  \n",
    "\n",
    "pip install mysqlclient==2.0.0  [--force-reinstall]  \n",
    "\n",
    "python -m ipykernel install [--user] --prefix=C:\\Users\\tech_expert\\.conda\\envs\\mysql-client --name mysql-client "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mThe kernel 'mysql-client (Python 3.7.12)' was not started as it is located in an insecure location 'c:\\ProgramData\\jupyter\\kernels\\mysql-client\\kernel.json'.  \n",
      "\u001b[1;31mClick <a href='https://aka.ms/JupyterTrustedKernelPaths'>here</a> for further details, optionally update the setting <a href='command:workbench.action.openSettings?[\"jupyter.kernels.trusted\"]'>jupyter.kernels.trusted</a> to trust the kernel."
     ]
    }
   ],
   "source": [
    "import pymysql\n",
    "from sqlalchemy import create_engine\n",
    "import pandas as pd\n",
    "from creds import server, user, pwd\n",
    "dialect = \"mysql\"\n",
    "driver = \"pymysql\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# format for connection url: “dialect+driver://username:password@host”\n",
    "engine = create_engine(f\"{dialect}+{driver}://{user}:{pwd}@{server}\", connect_args= dict(host=f'{server}', port=3306))\n",
    "conn = engine.connect()\n",
    "df = pd.read_sql('select * from my_db.temp_table', engine)\n",
    "print(df)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "works!  in \"mysql-python\" env (sqlalchemy=1.3.24, python=3.7.16), now working in \"mysql-client\" (sqlalchemy=1.4.42, python=3.7.12) env  \n",
    "   \n",
    "try downgrading mysql-client to sqlalchemy=1.3.24 - fixed it!  \n",
    "\n",
    "Force TCP socket. Notice the two uses of `?`  \n",
    "Normally URL options should use `?` and `&`    \n",
    "after that. But that doesn't work here (bug?)  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# format for connection url: “dialect+driver://username:password@host?host=host?port=port”\n",
    "engine = create_engine(f\"mysql+pymysql://{user}:{pwd}@{server}/my_db?host={server}?port=3306\")\n",
    "\n",
    "conn = engine.connect()\n",
    "result = conn.execute(\"select * from my_db.temp_table\")\n",
    "print(result.fetchall())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "\n",
    "(Pdb) conn = engine.connect()  \n",
    "*** sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, \"Access denied for user '{user}'@'localhost' (using password: YES)\")  \n",
    "(Background on this error at: http://sqlalche.me/e/13/e3q8)  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# format for connection url: “dialect+driver://username:password@host/database”\n",
    "engine = create_engine(f\"mysql+pymysql://{user}:{pwd}@{server}/my_db\")\n",
    "conn = engine.connect()\n",
    "result = conn.execute(\"select * from my_db.temp_table\")\n",
    "print(result.fetchall())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# format for connection url: “dialect+driver://username:password@host:port/database”\n",
    "engine = create_engine(f\"mysql+mysqlconnector://{user}:{pwd}@{server}:3306/my_db\")\n",
    "conn = engine.connect()\n",
    "result = conn.execute(\"select * from my_db.temp_table\")\n",
    "print(result.fetchall())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "try installing python=3.7.[1-16] to fix this - works now that i downgraded, and added mysqlclient=1.3.14 library, it must contain the missing authentication plugin  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# format for connection url: “dialect+driver://username:password@host:port/database”\n",
    "connection_string = f\"mysql+mysqlconnector://{user}:{pwd}@localhost:3306/my_db\"\n",
    "engine = create_engine(connection_string, echo=True)\n",
    "conn = engine.connect()\n",
    "result = conn.execute(\"select * from my_db.temp_table\")\n",
    "print(result.fetchall())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "old error:  \n",
    "*** sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2059 (HY000): Authentication plugin 'mysql_native_password' cannot be loaded: The specified module could not be found.  \n",
    "(Background on this error at: https://sqlalche.me/e/20/4xp6)   "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "both work, localhost = 127.0.0.1 - fixed when i run pip install mysqlclient==2.0.0  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# format for connection url: “dialect+driver://username:password@host:port”\n",
    "engine = create_engine(f\"mysql://{user}:{pwd}@127.0.0.1:3306/\")\n",
    "# engine = create_engine(f\"mysql://{user}:{pwd}@localhost:3306/\")\n",
    "conn = engine.connect()\n",
    "result = conn.execute(\"select * from my_db.temp_table\")\n",
    "print(result.fetchall())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "(Pdb) conn = engine.connect()  \n",
    "*** sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2006, 'SSL connection error: protocol version mismatch')  \n",
    "(Background on this error at: http://sqlalche.me/e/13/e3q8)  \n",
    "\n",
    "or   \n",
    "\n",
    "(Pdb) engine = create_engine(f\"mysql://{user}:{pwd}@localhost:3306/\")  \n",
    "ModuleNotFoundError: No module named 'MySQLdb'  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "mysql-python",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
